# Generated by Django 5.2.3 on 2025-09-25 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('lecturer', models.CharField(verbose_name='Lecturer')),
                ('day', models.CharField(verbose_name='Day')),
                ('name', models.CharField(verbose_name='Name')),
                ('time', models.CharField(verbose_name='Time')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='sites.site', verbose_name='related site')),
            ],
            options={
                'verbose_name': 'Lectures',
            },
        ),
    ]
